import { jsPDF } from "jspdf";
import "jspdf-autotable";

/**
 * Very basic markdown-to-PDF text renderer.
 * For a production app, use a real parser, but this fits our lightweight FinTrack style.
 */
export function generateFinancePDF(title: string, content: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(15, 118, 110); // primary teal color
  doc.text("FinTrack Report", margin, 25);

  doc.setFontSize(14);
  doc.setTextColor(60, 60, 60);
  doc.text(title, margin, 35);

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, 40, pageWidth - margin, 40);

  // Body content
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(40, 40, 40);

  // Simple markdown cleaning (strip # and *)
  const cleanContent = content
    .replace(/^#+ /gm, "")
    .replace(/^\* /gm, "• ")
    .replace(/\*\*(.*?)\*\*/g, "$1");

  const splitText = doc.splitTextToSize(cleanContent, pageWidth - margin * 2);
  
  let y = 50;
  splitText.forEach((line: string) => {
    if (y > 280) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += 6;
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by FinTrack AI • Page ${i} of ${pageCount}`, pageWidth / 2, 290, { align: "center" });
  }

  doc.save(`${title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_report.pdf`);
}
